### PR TITLE
Add 3 vs 4 days

### PR DESCRIPTION
**Pull request by rwdavies**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Can you resolve the conflicts please @rwdavies?

**Comment by jeromekelleher** [comment]
It's a bit easier to work with if lines are spilt at a reasonable length also (~100, say)

**Comment by rwdavies** [comment]
There is no difference, I just added this line "Please note that those who booked 4 nights of accomodation are checked in from March 27th through March 31st, while those who booked 3 nights of accomodation are checked in from March 28th through March 31st."

**Comment by jeromekelleher** [comment]
UPdated separately

**Pull request closed without merging**
